//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steamp3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steamp3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Colors {
            get {
                object obj = ResourceManager.GetObject("Colors", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] LiveUpdate {
            get {
                object obj = ResourceManager.GetObject("LiveUpdate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarFull {
            get {
                object obj = ResourceManager.GetObject("StarFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarHalf {
            get {
                object obj = ResourceManager.GetObject("StarHalf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StarNone {
            get {
                object obj = ResourceManager.GetObject("StarNone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Steamp3.Skin Name=&quot;Steam&quot; Author=&quot;Valve&quot;&gt;
        ///  &lt;Button BGColor=&quot;686562&quot; BGColor2=&quot;4c4a48&quot; BorderColor=&quot;706d69&quot; TextColor=&quot;d1cfcd&quot;&gt;
        ///    &lt;Down BGColor=&quot;4c4a48&quot; BGColor2=&quot;686562&quot; BorderColor=&quot;99938d&quot; TextColor=&quot;d1cfcd&quot; /&gt;
        ///    &lt;Over BGColor=&quot;686562&quot; BGColor2=&quot;4c4a48&quot; BorderColor=&quot;99938d&quot; TextColor=&quot;ffffff&quot; /&gt;
        ///  &lt;/Button&gt;
        ///
        ///  &lt;CheckBox BorderColor=&quot;4d4b48&quot; TextColor=&quot;b0aeae&quot;&gt;
        ///    &lt;Down BorderColor=&quot;99938d&quot; TextColor=&quot;ffffff&quot; /&gt;
        ///    &lt;Over BorderColor=&quot;99938d&quot; TextColor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Steam {
            get {
                return ResourceManager.GetString("Steam", resourceCulture);
            }
        }
    }
}
